travis:
  secure:
    BINSTAR_TOKEN: MrL6n2M4oujAxy5fio/CIH3LEPqj1vHrHbs+adUqGU0Jd2gVM2vzzn3W7HaBev4SEQQ+u5xms6jUXjLdp2E3rSnc2O0lYXGC976KoekZ6pALNMIhu+nnVOpY0kgDR6539gzAgjSHuu3X2GvulO7l9xX9TppZ1K4UheGnGr8OqkcCeJpovsgn4hgi+euorOHs9RmiwZxf8Ymkt6IAp8kTz+Y9+VfpsVUwh+vkEmsymxDuKyYIF3ZqGmsrelJ1jWe33U+STanEp0TW5cip+1YU7IjE9tPi3LlOi66fk7IN36nwQKtKUCxPxr1uPa3NEIwlVyak6ExKsTxyQZ7MzWp+iL9fCICG/d5uLoSRtBnNc+AxdobCoVloEoTDD5sFMBle9j9WKX2+nR5pA3iiL4FbQZLJXU7QohzRmYkcHKWzqCA8/R8moCQ01StH4ExksRTcrR5/14YT2BPH4U64xzojG3OdjB9ByMv3bNYW4fzTRQ8XIIe+Mh21g5X6Od8J9RM4G76tCea57mYV0jOimuh3sE0WS0lIuBCjMezWejt3EMtR6MuIVSPTAa9ahoYGbLL57a3UDPs7JqOpD9S1QOrr20GHw5KCkd+bL4Zny4RzwLlL11FCq2qxyTkAfUyxm078XMOiPHvPPY7W7CR8fRQW43q5DrzyOVszry5VemKva24=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
